# Dependencies
markdown:       kramdown
highlighter: 	rouge
gems: 		[jekyll-sitemap, jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            'brontolabs'
tagline:          'Linux, Blender, Video, Web, Stuff'
description:      'brontosaurusrex.github.io'
url:              http://brontosaurusrex.github.io

author:
  name:           'brontosaurusrex'
  url:            http://brontosaurusrex.github.io

paginate:         7

# Custom vars

github:
  repo:           https://github.com/brontosaurusrex/postbang

prose:
  rooturl: '_posts'
  siteurl: 'http://brontosaurusrex.github.io/'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "date"
        field:
          element: "hidden"
          value: "CURRENT_DATETIME"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
             - name: "Linux"
              value: "linux"
             - name: "Blender"
              value: "blender"
             - name: "Video"
              value: "video"
             - name: "Audio"
              value: "audio"
             - name: "Cli"
              value: "cli"
             - name: "Misc"
              value: "misc"
