# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            brontosaurusrex.github.io
tagline:          'Linux, Video, Audio'
description:      'Worst blog in the universe.'
url:              http://brontosaurusrex.github.io

author:
  name:           'brontosaurusrex'
  url:            http://brontosaurusrex.github.io

paginate:         7

# Custom vars

github:
  repo:           https://github.com/brontosaurusrex/postbang
