# Dependencies
markdown:       kramdown
highlighter: 	rouge
gems: 		[jekyll-sitemap, jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            'brontolabs'
tagline:          'Improvise. Adapt. Overcome.'
description:      'brontosaurusrex.github.io'
url:              http://brontosaurusrex.github.io

author:
  name:           'brontosaurusrex'
  url:            http://brontosaurusrex.github.io

paginate:         7


