# Dependencies
markdown:       redcarpet
highlighter: 	pygments
gems: 		[jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            brontosaurusrex.github.io
tagline:          'Linux, Video, Audio'
description:      'brontosaurusrex.github.io'
url:              http://brontosaurusrex.github.io

author:
  name:           'brontosaurusrex'
  url:            http://brontosaurusrex.github.io

paginate:         7

# Custom vars

github:
  repo:           https://github.com/brontosaurusrex/postbang

gems: 
  - jekyll-sitemap

prose:
  rooturl: '_posts'
  siteurl: 'http://brontosaurusrex.github.io/'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "time"
        field:
          element: "hidden"
          value: "CURRENT_DATETIME"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
