# Site settings
title: http://brontosaurusrex.github.io
email: your_email@example.com
author: brontosaurusrex
description: "Linux, Video, Audio"
baseurl: ""
url: "http://brontosaurusrex.github.io"
google_analytics: 

# Build settings
markdown: kramdown
permalink: pretty
paginate: 7
