excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://brontosaurusrex.github.io
title: brontosaurusrex
tagline: Linux and video and stuff
description: The world's best GitHub blog.
paginate: 5
