# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            brontosaurusrex.github.io
tagline:          'Linux, Video, Audio'
description:      'Worst blog in the universe.'
url:              http://brontosaurusrex.github.io

author:
  name:           'unnamed'
  url:            ttp://brontosaurusrex.github.io

paginate:         5

# Custom vars
version:          

github:
  repo:           https://github.com/brontosaurusrex/postbang
